version: '3.8'
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass test
    ports:
    - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.8.19-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
